### PR TITLE
updated data download, aded conda yml and updated README

### PR DESCRIPTION
**Pull request by rohandavidg**
Updated the README to have instructions for running DrugCell in a container/ conda and pip

### CODE REVIEW

**Comment by RylieWeaver** [comment]
I got this error when trying to run after using the feature/early_stop .yml file to make the environment:

``ModuleNotFoundError: No module named 'torchmetrics'``


Are you sure you want to take it out?

**Comment by RylieWeaver** [comment]
This is fixed when I do your recommended steps. Probably this one in particular:
```
python3 -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 torchmetrics==0.11.1 --extra-index-url https://download.pytorch.org/whl/cu113
```
Maybe make it a required step?

**Comment by rohandavidg** [comment]
torchmetrics metrics shouldnt be in .yml file

**Review by wilke — APPROVED** [review]
LGTM

**Pull request merged**
